name: loading_pulse
description: "Loading pulse animation."
version: 0.0.2
homepage: https://github.com/GioRey/loading_pulse

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
